name: CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-deploy:
    name: Build-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: CI= npm run build

      - name: Deploy
        uses: prewk/s3-cp-action@v2
        with:
          aws_s3_endpoint: ${{ secrets.ENDPOINT_URL }}
          aws_region: ${{ secrets.AWS_REGION_NAME }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          source: "./build"
          dest: "s3://${{ secrets.S3_BUCKET }}"
          flags: --recursive
